on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        feature: ["", "-all"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        python -m pip install --upgrade pip
        make bootstrap${{ matrix.feature }}
    - run: |
        make test${{ matrix.feature }}

  glob_contrib:
    runs-on: ubuntu-latest
    outputs:
      extras: ${{ steps.set-matrix.outputs.extras }}
    steps:
    - uses: actions/checkout@v2
    - id: set-matrix
      run: |
        make lint-contrib
        echo "::set-output name=extras::$(ls requirements/*/extra.txt | cut -d '/' -f 2 | jq -Rsc 'split("\n")[:-1]')"

  test_contrib:
    runs-on: ubuntu-latest
    needs: glob_contrib
    strategy:
      matrix:
        extra: ${{ fromJSON(needs.glob_contrib.outputs.extras) }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: |
        python -m pip install --upgrade pip
        make bootstrap
        make bootstrap-contrib-${{ matrix.extra }}
    - run: |
        make test-contrib-${{ matrix.extra }}

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        make upload

    - run:
        make tag
